// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdmFHH-zjr1wUBtd4IkJql_hcitoP5Ao',
    appId: '1:738249251640:web:7f3c449f4f7b7f5d4c3fcd',
    messagingSenderId: '738249251640',
    projectId: 'spark-b0c5b',
    authDomain: 'spark-b0c5b.firebaseapp.com',
    storageBucket: 'spark-b0c5b.appspot.com',
    measurementId: 'G-Y91Z73G3W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfcJ4vF8zX4ofDi9H1rWVifZ0kJkTlJc',
    appId: '1:738249251640:android:00b7bbb46532e8d94c3fcd',
    messagingSenderId: '738249251640',
    projectId: 'spark-b0c5b',
    storageBucket: 'spark-b0c5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHjgr8wCIpDRc3dy6EfUI3MLf9rntkh-M',
    appId: '1:738249251640:ios:815ea218701aad734c3fcd',
    messagingSenderId: '738249251640',
    projectId: 'spark-b0c5b',
    storageBucket: 'spark-b0c5b.appspot.com',
    iosClientId: '738249251640-elnbesp012iuh08ut6101cvj72nqbuie.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHjgr8wCIpDRc3dy6EfUI3MLf9rntkh-M',
    appId: '1:738249251640:ios:93a6b0cf6b74e99c4c3fcd',
    messagingSenderId: '738249251640',
    projectId: 'spark-b0c5b',
    storageBucket: 'spark-b0c5b.appspot.com',
    iosClientId: '738249251640-93lb3kqls4uv58l7j48e17ae0n6n17tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
